const languageCompilerList = {
  C: { compiler: 'gcc-11.1.0-c' },
  'C++': { compiler: 'gcc-11.1.0' },
  'C#': { compiler: 'mono-6.12.0.122' },
  Erlang: { compiler: 'erlang-23.3.1' },
  Elixir: { compiler: 'elixir-1.11.4' },
  Haskell: { compiler: 'ghc-9.0.1' },
  D: { compiler: 'dmd-2.096.0' },
  Java: { compiler: 'openjdk-jdk-15.0.3+2' },
  Rust: { compiler: 'rust-1.51.0' },
  Python: { compiler: 'cpython-3.10.2' },
  Ruby: { compiler: 'ruby-3.1.0' },
  Scala: { compiler: 'scala-2.13.5' },
  Groovy: { compiler: 'groovy-3.0.8' },
  JavaScript: { compiler: 'nodejs-16.14.0' },
  Swift: { compiler: 'swift-5.3.3' },
  Perl: { compiler: 'perl-5.34.0' },
  PHP: { compiler: 'php-8.0.3' },
  Lua: { compiler: 'lua-5.4.3' },
  SQL: { compiler: 'sqlite-3.35.5' },
  Pascal: { compiler: 'fpc-3.2.0' },
  Lisp: { compiler: 'clisp-2.49' },
  'Lazy K': { compiler: 'lazyk' },
  'Vim script': { compiler: 'vim-8.2.2811' },
  OCaml: { compiler: 'ocaml-4.12.0' },
  Go: { compiler: 'go-1.16.3' },
  'Bash': { compiler: 'bash' },
  Pony: { compiler: 'pony-0.39.1' },
  Crystal: { compiler: 'crystal-1.0.0' },
  Nim: { compiler: 'nim-1.6.4' },
  OpenSSL: { compiler: 'openssl-1.1.1k' },
  R: { compiler: 'r-4.0.5' },
  TypeScript: { compiler: 'typescript-4.2.4' },
  Julia: { compiler: 'julia-1.6.1' }
}

const languageAliasMap = {
  C: 'C',
  c: 'C',
  'C++': 'C++',
  cpp: 'C++',
  'c++': 'C++',
  CPP: 'C++',
  'C#': 'C#',
  csharp: 'C#',
  cs: 'C#',
  dotnet: 'C#',
  'c#': 'C#',
  CSHARP: 'C#',
  CS: 'C#',
  DOTNET: 'C#',
  Erlang: 'Erlang',
  erlang: 'Erlang',
  ERLANG: 'Erlang',
  Elixir: 'Elixir',
  elixir: 'Elixir',
  ELIXIR: 'Elixir',
  Haskell: 'Haskell',
  haskell: 'Haskell',
  hs: 'Haskell',
  HASKELL: 'Haskell',
  HS: 'Haskell',
  D: 'D',
  d: 'D',
  Java: 'Java',
  java: 'Java',
  JAVA: 'Java',
  Rust: 'Rust',
  rust: 'Rust',
  RUST: 'Rust',
  Python: 'Python',
  python: 'Python',
  py: 'Python',
  PYTHON: 'Python',
  PY: 'Python',
  Ruby: 'Ruby',
  ruby: 'Ruby',
  rb: 'Ruby',
  RUBY: 'Ruby',
  RB: 'Ruby',
  Scala: 'Scala',
  scala: 'Scala',
  SCALA: 'Scala',
  Groovy: 'Groovy',
  groovy: 'Groovy',
  GROOVY: 'Groovy',
  JavaScript: 'JavaScript',
  javascript: 'JavaScript',
  js: 'JavaScript',
  JAVASCRIPT: 'JavaScript',
  JS: 'JavaScript',
  Swift: 'Swift',
  swift: 'Swift',
  SWIFT: 'Swift',
  Perl: 'Perl',
  perl: 'Perl',
  PERL: 'Perl',
  PHP: 'PHP',
  php: 'PHP',
  Lua: 'Lua',
  lua: 'Lua',
  LUA: 'Lua',
  SQL: 'SQL',
  sql: 'SQL',
  Pascal: 'Pascal',
  pascal: 'Pascal',
  objectpascal: 'Pascal',
  PASCAL: 'Pascal',
  OBJECTPASCAL: 'Pascal',
  Lisp: 'Lisp',
  lisp: 'Lisp',
  emacs: 'Lisp',
  elisp: 'Lisp',
  'emacs-lisp': 'Lisp',
  LISP: 'Lisp',
  EMACS: 'Lisp',
  ELISP: 'Lisp',
  'EMACS-LISP': 'Lisp',
  OCaml: 'OCaml',
  ocaml: 'OCaml',
  OCAML: 'OCaml',
  Go: 'Go',
  go: 'Go',
  GO: 'Go',
  Bash: 'Bash',
  bash: 'Bash',
  shell: 'Bash',
  BASH: 'Bash',
  SHELL: 'Bash',
  Crystal: 'Crystal',
  crystal: 'Crystal',
  CRYSTAL: 'Crystal',
  Nim: 'Nim',
  nim: 'Nim',
  NIM: 'Nim',
  R: 'R',
  r: 'R',
  TypeScript: 'TypeScript',
  typescript: 'TypeScript',
  ts: 'TypeScript',
  TYPESCRIPT: 'TypeScript',
  TS: 'TypeScript',
  Julia: 'Julia',
  julia: 'Julia',
  JULIA: 'Julia'
}

export { languageCompilerList, languageAliasMap};


